print("===survay===\n")
name= input("Enter your name: ")
fvrt_food= input("Enter your favorite food: ")
birth_year= input("Enter your birth year: ") 
fvrt_num= input("Enter your favorite number: ")
language= input("Enter your favorite programming language: ")
print("\n=== Print Result===\n")
print(f"Name: {name}")
print(f"Favorite Food: {fvrt_food}")
print(f"Birth Year: {birth_year}")
print(f"Favorite Number: {fvrt_num}")
print(f"Favorite Programming Language: {language}")
print("\n=== Thanks ===\n") 